### ISSUE TITLE
hubic-wrapper-to-swift in production

### ISSUE THREAD

**Issue by szepeviktor** [puzzle1536/hubic-wrapper-to-swift#18]
A couple of days ago hubic-wrapper-to-swift is in production (backup of remote DB-s).
Could you please explain this cron output to me?

```
Traceback (most recent call last):
  File "/usr/local/bin/hubic.py", line 582, in <module>
    hubic.swift(args)
  File "/usr/local/bin/hubic.py", line 462, in swift
    subprocess.call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by szepeviktor** [comment]
For googlers:
`X-Cron-Env: <PATH=/usr/bin:/bin>`

```
# which swift
/usr/local/bin/swift
```

**Comment by szepeviktor** [comment]
```bash
# local swift command
PATH=${PATH}:/usr/local/bin
```

**Comment by molobrakos** [comment]
Maybe a more friendly error message would be in place instead of this exception: "swift binary not found, please check your path."

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Or a configurable swift client path.
