### ISSUE TITLE
Exit code

### ISSUE THREAD

**Issue by szepeviktor** [puzzle1536/hubic-wrapper-to-swift#21]
```bash
if !  /usr/local/bin/hubic.py --config=/home/bck/database/.hubic.cfg --swift -- -q upload --object-name workwear/workwear-00000.zpaq db-ftp workwear-00000.zpaq > /dev/null; then
    echo "Archive upload failed ${ID}/${ZPAQ}." >&2
fi
rm "$ZPAQ"
```
Returned no error!
```
Traceback (most recent call last):
  File "/usr/local/bin/swift", line 11, in <module>
    sys.exit(main())
  File "/opt/python-3.4.3/lib/python3.4/site-packages/swiftclient/shell.py", line 1309, in main
    globals()['st_%s' % args[0]](parser, argv[1:], output)
  File "/opt/python-3.4.3/lib/python3.4/site-packages/swiftclient/shell.py", line 838, in st_upload
    msg += error.http_response_content[:60]
TypeError: Can't convert 'bytes' object to str implicitly
```
What is the problem here? HubiC error?
How can we get a non-zero error code?

**Comment by szepeviktor** [comment]
https://bugs.launchpad.net/python-swiftclient/+bug/1457012

**Comment by szepeviktor** [comment]
@puzzle1536 The same error today.
Could you help?
